words:
  - abdet
  - abig
  - ablen
  - adet
  - adjacences
  - adxbdy
  - adxcdy
  - adxt
  - adxtail
  - adyt
  - adytail
  - ampty
  - applicata
  - assignes
  - bctlen
  - bcxtail
  - bdet
  - bdrs
  - bdxady
  - bdxcdy
  - bdxt
  - bdxtail
  - bdyt
  - bdytail
  - blarge
  - buco
  - ccweb
  - cdet
  - cdiv
  - cdxady
  - cdxbdy
  - cdxt
  - cdyt
  - cdytail
  - cdztail
  - cgal
  - choco
  - clarge
  - coeffs
  - cosx
  - crds
  - csave
  - d'appoggio
  - degn
  - delle
  - dlength
  - dorientation
  - dtype
  - duplicte
  - eindex
  - estm
  - evarr
  - evecs
  - fesze
  - findex
  - fnow
  - foreachveedge
  - foreachvvvertex
  - ftst
  - gmpq
  - gmpz
  - gomod
  - hindex
  - icceb
  - imat
  - imati
  - interni
  - invertes
  - isnegative
  - ispeb
  - istituto
  - jeremie
  - jkkname
  - jlist
  - jqsort
  - jswap
  - lazynt
  - lexycographic
  - lexycographically
  - liblaf
  - likned
  - loro
  - matematica
  - maxz
  - minda
  - miny
  - minz
  - nazionale
  - nedg
  - neghborhood
  - nfname
  - nnor
  - ntin
  - numrays
  - numtris
  - nuova
  - nuovi
  - ocds
  - oceil
  - oname
  - operatior
  - orat
  - oriantation
  - ottimizzo
  - ovbs
  - oved
  - ovps
  - ovpsi
  - pnnt
  - pnos
  - polygonized
  - ponts
  - posizione
  - posto
  - proietto
  - punti
  - qnew
  - qstatus
  - quella
  - regione
  - resonable
  - retriangulate
  - retriangulated
  - retriangulates
  - riporto
  - rline
  - secondo
  - seze
  - sezione
  - shewchuk
  - sinx
  - specifyed
  - splitvs
  - splt
  - stin
  - tbds
  - tecnologie
  - threchold
  - tmesh
  - tname
  - tnor
  - totoggle
  - tounmark
  - trdc
  - trhough
  - trianglation
  - triangoli
  - trianlge
  - tris
  - tstruct
  - ttbr
  - tvol
  - uctype
  - unoriented
  - unproperly
  - upheap
  - vari
  - vecs
  - vertici
  - vincolato
  - vlength
  - voronoi
  - voxel
  - wlength
ignorePaths:
  - "*-lock.*"
  - "*.lock"
dictionaries:
  - bash
  - cpp
  - cpp-legacy
  - cpp-refined
  - css
  - data-science
  - dotnet
  - en-gb
  - java
  - makefile
  - npm
  - python
  - python-common
  - r
allowCompoundWords: true
