version: "3"

tasks:
  build:
    cmds:
      - cmake -S="MeshFix-V2.1" -B="build"
      - cmake --build "build" --parallel

  clean:
    cmds:
      - git -C "MeshFix-V2.1" clean -d --force -x
      - git clean -d --force -X

  dist:
    cmds:
      - cmd: |
          if [[ -s "MeshFix-V2.1/bin64/Debug/MeshFix{{exeExt}}" ]]; then
            source="MeshFix-V2.1/bin64/Debug/MeshFix{{exeExt}}"
          elif [[ -s "MeshFix-V2.1/bin64/MeshFix{{exeExt}}" ]]; then
            source="MeshFix-V2.1/bin64/MeshFix{{exeExt}}"
          else
            echo "MeshFix.exe not found"
            exit 1
          fi
          install -D --no-target-directory --verbose "$source" "dist/MeshFix-{{OS}}-{{ARCH}}{{exeExt}}"
        silent: true
    deps:
      - build
    generates:
      - dist/MeshFix-{{OS}}-{{ARCH}}{{exeExt}}
