name: CI

on:
  push:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install GNU Softwares
        uses: liblaf/template/.github/actions/install@main
        with:
          brew: coreutils make
          choco: gnuwin32-coreutils.install make
      - name: Build
        run: make dist
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-${{ runner.arch }}
          path: dist/*
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

  release:
    name: Release
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: version
        name: Read Version
        run: echo "version=$(cat version.txt)" >> "$GITHUB_OUTPUT"
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: Create Release
        uses: softprops/action-gh-release@master
        with:
          files: artifacts/**/*
          tag_name: v${{ steps.version.outputs.version }}
